### ISSUE TITLE
Ошибка 500 /1346-fotokollektsiya-koloritnyh-zhiguley-samogo-massovogo-sovetskogo-avtomobilya

### ISSUE THREAD

**Issue by tonyrewin** [Discours/discoursio-web#30]
QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00

**Comment by tonyrewin** [comment]
`ClientError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r): {"response":{"data":null,"errors":[{"message":"QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)"`

**Comment by knst-kotov** [comment]
увеличен лимит соединений к БД
https://github.com/Discours/discours-backend/commit/47364e37f4b2b7d7753e160229b70fa6d0f0d699
